volumes:
  rabbitmq_data:

services:
  ##################################
  # Pytest on Food Rescue Service
  ##################################
  workshop-part-pytest:
    build:
      context: ../
      dockerfile: ci/Dockerfile.test
    environment:
      rabbitmq_host: rabbitmq
      rabbitmq_port: 5672
      stage: test
      workshop_service_url: http://localhost:5001

  ####################################
  # RabbitMQ: The messaging broker
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
